# Generated by Django 4.1.6 on 2023-02-24 12:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('slug', models.SlugField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blogImages')),
                ('title', models.CharField(max_length=100, verbose_name='Blog Title')),
                ('summary', models.CharField(max_length=200, verbose_name='Blog Summary')),
                ('text', models.TextField(verbose_name='Blog Text')),
                ('slug', models.SlugField(default='', unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('categorys', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.blogcategory')),
            ],
        ),
    ]
